### ISSUE TITLE
Cannot run in simulator

### ISSUE THREAD

**Issue by tolidano** [MyOwnClone/quake_watch#3]
I am on an M1 with Xcode 13.4.1 (13F100)

I opened the project and hit "Run"
It launched an Apple Watch 7 device and then showed this error:

"Please try again later.
WatchKit 2 app extension's NSExtension.NSExtensionAttributes.WKAppBundleIdentifier value does not match WatchKit app's bundle ID (found "com.myownclone.qwatch.watchkitapp"; expected "qwatch.watchkitapp")."

Any ideas?

**Comment by MyOwnClone** [comment]
I am not on my Mac right now (so I am making up this from memory), but basically you have to go to the project (or target) settings under the "Signing" (or something similar) section and make your own bundle name (i.e. com.<yourself>.qwatch.watchkitapp) and replace all instances of "qwatch.watchkitapp" with that string. I basically removed my bundle/id setup before publishing on github, but it was probably done inconsistently. Please let me know if that helped!

**Comment by tolidano** [comment]
qwatch WatchKit Extension -> Info.plist -> WKAppBundleIdentifier had com.myownclone still. Once removed, it ran fine in the simulator. Awesome work! Once I had all the provisioning certificate stuff set up (I let Xcode manage all of it, just choosing my team), I was able to deploy it to my device. This is confirmed to work via iPhone 12 Pro iOS 15.6.1 Apple Watch 7 watchOS 8.7 (19U66)

**Comment by MyOwnClone** [comment]
Thanks for the info, great to hear that!

**Comment by Networkwilliams** [comment]
Hi just trying to follow this issue and fix. Not sure where I find the WKAppBundleIdentifier file

Can you please help 

Thanks

**Comment by tolidano** [comment]
Click on the project in Xcode and you will see qwatch WatchKit Extension so click that and see Info.plist and look for WKAppBundleIdentifier

**Comment by Networkwilliams** [comment]
> Click on the project in Xcode and you will see qwatch WatchKit Extension so click that and see Info.plist and look for WKAppBundleIdentifier

Hiya

Manage to sort that out thanks but not struggling with the signing 

I'm getting this error message 

```
Failed to register bundle identifier
The app identifier "qwatch" cannot be registered to your development team because it is not available. Change your bundle identifier to a unique string to try again.
```
